/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PC_OTA_USING_ANT;

import com.fazecast.jSerialComm.SerialPort;
import java.io.*;
import java.lang.reflect.InvocationTargetException;
import java.nio.file.Files;
import java.util.concurrent.TimeUnit;
import java.util.logging.*;
import javax.swing.*;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static PC_OTA_USING_ANT.OTA_PC.*;
import java.awt.Image;
import javax.imageio.ImageIO;

public class BootloaderGUI extends javax.swing.JFrame {

    static SerialPort SelectedSerial;
    static SerialPort Ports[];
    static File file = null;
    static OutputStream MyOutputStream;
    static InputStream MyInputStream;
    static byte TotalAPPCode[];
    static int CurrentDataSize = 0;
    static int Position = 0;
    static byte response = OTA_ERROR_OK;

    public class WorkOnEventThread {

        void UpdateTextArea(String s) throws InterruptedException, InvocationTargetException {
            SwingUtilities.invokeAndWait(new Runnable() {
                @Override
                public void run() {
                    jTextArea_OutputScreen.append(s);
                }
            });
        }
    }

    /**
     * Creates new form BootloaderGUI
     * @throws java.io.IOException
     */
    public BootloaderGUI() throws IOException {
        initComponents();
        try{
        Image img=ImageIO.read(getClass().getResource("/images/icon.png"));
        this.setIconImage(img);
        }catch(Exception e){
            
        }
        Ports = SerialPort.getCommPorts();
        jTextArea_OutputScreen.setEditable(false);
        jComboBox_BaudRate.setSelectedItem("9600");
        jComboBox_DataBits.setSelectedItem("8");
        jComboBox_ParityBits.setSelectedItem("NO_PARITY");
        jComboBox_StopBits.setSelectedItem("1");
        jProgressBar_ComStatus.setValue(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton_OpenFile = new javax.swing.JButton();
        jButton_Disconnect = new javax.swing.JButton();
        jButton_Connect = new javax.swing.JButton();
        jTextField_FilePath = new javax.swing.JTextField();
        jButton_StartFlashing = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_ComPort = new javax.swing.JComboBox<>();
        jComboBox_BaudRate = new javax.swing.JComboBox<>();
        jComboBox_DataBits = new javax.swing.JComboBox<>();
        jComboBox_ParityBits = new javax.swing.JComboBox<>();
        jComboBox_StopBits = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jProgressBar_ComStatus = new javax.swing.JProgressBar();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_OutputScreen = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BLUETOOTH_FOTA");
        setBackground(new java.awt.Color(39, 40, 34));
        setForeground(new java.awt.Color(39, 40, 34));

        jPanel3.setBackground(new java.awt.Color(39, 40, 34));

        jPanel2.setBackground(new java.awt.Color(39, 40, 34));

        jLabel6.setBackground(new java.awt.Color(39, 40, 34));
        jLabel6.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(141, 208, 6));
        jLabel6.setText("MadeBy:AhmedElhamy 2022 ");

        jButton_OpenFile.setBackground(new java.awt.Color(204, 255, 204));
        jButton_OpenFile.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_OpenFile.setForeground(new java.awt.Color(0, 0, 0));
        jButton_OpenFile.setText("OPEN FILE");
        jButton_OpenFile.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_OpenFile.setFocusPainted(false);
        jButton_OpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OpenFileActionPerformed(evt);
            }
        });

        jButton_Disconnect.setBackground(new java.awt.Color(153, 0, 51));
        jButton_Disconnect.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_Disconnect.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Disconnect.setText("Disconnect");
        jButton_Disconnect.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_Disconnect.setFocusPainted(false);
        jButton_Disconnect.setRequestFocusEnabled(false);
        jButton_Disconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DisconnectActionPerformed(evt);
            }
        });

        jButton_Connect.setBackground(new java.awt.Color(0, 153, 153));
        jButton_Connect.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_Connect.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Connect.setText("Connect");
        jButton_Connect.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_Connect.setFocusPainted(false);
        jButton_Connect.setRequestFocusEnabled(false);
        jButton_Connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConnectActionPerformed(evt);
            }
        });

        jTextField_FilePath.setText("The Selected File Path");
        jTextField_FilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FilePathActionPerformed(evt);
            }
        });

        jButton_StartFlashing.setBackground(new java.awt.Color(102, 102, 102));
        jButton_StartFlashing.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jButton_StartFlashing.setForeground(new java.awt.Color(255, 255, 255));
        jButton_StartFlashing.setText("START FLASHING");
        jButton_StartFlashing.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_StartFlashing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StartFlashingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_Connect, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField_FilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_OpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton_StartFlashing, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_FilePath)
                    .addComponent(jButton_Connect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Disconnect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jButton_OpenFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jButton_StartFlashing, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(39, 40, 34));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "COM PORT SETTINGS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(141, 208, 6));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(141, 208, 6));
        jLabel1.setText("COM PORT");

        jLabel2.setBackground(new java.awt.Color(141, 208, 6));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(141, 208, 6));
        jLabel2.setText("BAUD RATE");

        jLabel3.setBackground(new java.awt.Color(141, 208, 6));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(141, 208, 6));
        jLabel3.setText("DATA BITS");

        jLabel4.setBackground(new java.awt.Color(141, 208, 6));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(141, 208, 6));
        jLabel4.setText("PARITY BITS");

        jLabel5.setBackground(new java.awt.Color(141, 208, 6));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(141, 208, 6));
        jLabel5.setText("STOP BITS");

        jComboBox_ComPort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SelectCom" }));
        jComboBox_ComPort.setFocusable(false);
        jComboBox_ComPort.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox_ComPortPopupMenuWillBecomeVisible(evt);
            }
        });

        jComboBox_BaudRate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4800", "9600", "38400", "57600", "115200" }));
        jComboBox_BaudRate.setFocusable(false);

        jComboBox_DataBits.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9" }));
        jComboBox_DataBits.setFocusable(false);
        jComboBox_DataBits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_DataBitsActionPerformed(evt);
            }
        });

        jComboBox_ParityBits.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO_PARITY", "EVEN_PARITY", "ODD_PARITY", " " }));
        jComboBox_ParityBits.setFocusable(false);

        jComboBox_StopBits.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "1.5", "2" }));
        jComboBox_StopBits.setFocusable(false);

        jLabel7.setBackground(new java.awt.Color(141, 208, 6));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(141, 208, 6));
        jLabel7.setText("COM STATUS");

        jProgressBar_ComStatus.setBackground(new java.awt.Color(255, 51, 51));
        jProgressBar_ComStatus.setForeground(new java.awt.Color(0, 255, 51));
        jProgressBar_ComStatus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_ComPort, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_BaudRate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_DataBits, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_ParityBits, 0, 127, Short.MAX_VALUE)
                            .addComponent(jComboBox_StopBits, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jProgressBar_ComStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_ComPort))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_BaudRate))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_DataBits))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_ParityBits))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_StopBits))
                .addGap(18, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar_ComStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(39, 40, 34));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "STATUS OUTPUT SCREEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jTextArea_OutputScreen.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea_OutputScreen.setColumns(20);
        jTextArea_OutputScreen.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N
        jTextArea_OutputScreen.setForeground(new java.awt.Color(141, 208, 6));
        jTextArea_OutputScreen.setRows(5);
        jTextArea_OutputScreen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea_OutputScreen.setHighlighter(null);
        jScrollPane1.setViewportView(jTextArea_OutputScreen);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(0, 255, 204));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_DisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DisconnectActionPerformed
        // TODO add your handling code here:
        if (SelectedSerial.isOpen()) {
            SelectedSerial.closePort();
            jComboBox_ComPort.setEnabled(true);
            jProgressBar_ComStatus.setValue(0);
            jButton_Disconnect.setEnabled(false);
            jTextArea_OutputScreen.append("Com Port is Disconnected\n");
        }
    }//GEN-LAST:event_jButton_DisconnectActionPerformed

    private void jButton_ConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConnectActionPerformed
        // TODO add your handling code here:
        try {

            SelectedSerial = Ports[jComboBox_ComPort.getSelectedIndex()];
            SelectedSerial.setBaudRate(Integer.parseInt(jComboBox_BaudRate.getSelectedItem().toString()));
            SelectedSerial.setNumDataBits(Integer.parseInt(jComboBox_DataBits.getSelectedItem().toString()));
            SelectedSerial.setNumStopBits(Integer.parseInt(jComboBox_StopBits.getSelectedItem().toString()));
            SelectedSerial.setParity(jComboBox_ParityBits.getSelectedIndex());

            if (SelectedSerial.openPort()) {
                SelectedSerial.setComPortTimeouts(SerialPort.TIMEOUT_READ_SEMI_BLOCKING, 0, 0);
                jComboBox_ComPort.setEnabled(false);
                jProgressBar_ComStatus.setValue(100);
                jButton_Disconnect.setEnabled(true);
                jTextArea_OutputScreen.append("Com Port is Connected\n");
                MyOutputStream = SelectedSerial.getOutputStream();
                MyInputStream = SelectedSerial.getInputStream();
            } else {
                jTextArea_OutputScreen.append("Com Port Failed to open !!!!!!!!");
            }
        } catch (ArrayIndexOutOfBoundsException a) {
            JOptionPane.showMessageDialog(this, " Error please choose COM Port", "ERROR", ERROR_MESSAGE);
        } catch (Exception b) {
            JOptionPane.showMessageDialog(this, b, " ERROR", ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButton_ConnectActionPerformed

    private void jTextField_FilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FilePathActionPerformed

    private void jComboBox_DataBitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_DataBitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_DataBitsActionPerformed

    private void jComboBox_ComPortPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox_ComPortPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        jComboBox_ComPort.removeAllItems();
        for (SerialPort Port : Ports) {
            jComboBox_ComPort.addItem(Port.getSystemPortName());
        }
    }//GEN-LAST:event_jComboBox_ComPortPopupMenuWillBecomeVisible

    private void jButton_StartFlashingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StartFlashingActionPerformed
        // TODO add your handling code here:
        MyOutputStream = SelectedSerial.getOutputStream();
        MyInputStream = SelectedSerial.getInputStream();
        jTextArea_OutputScreen.append("START FLASHING YOUR CODE THROUGH BLUETOOTH...\n");
        new SwingWorker() {
            @Override
            public Object doInBackground() throws InvocationTargetException {

                if (file != null) {

                    try {
                        new WorkOnEventThread().UpdateTextArea("Sending Start Packet...\n");
                        response = OTA_SendCMDPacket(OTA_CMD_START);

                        if (response == OTA_ERROR_OK) {
                            new WorkOnEventThread().UpdateTextArea("You Reseived ACK response\n");
                        } else {
                            new WorkOnEventThread().UpdateTextArea("You Reseived NACK response\n");
                        }

                        TimeUnit.MILLISECONDS.sleep(10);
                        new WorkOnEventThread().UpdateTextArea("Sending Header Packet...\n");
                        response = OTA_SendHeaderPacket(TotalAPPCode.length, 0);
                        if (response == OTA_ERROR_OK) {
                            new WorkOnEventThread().UpdateTextArea("You Reseived ACK response\n");
                        } else {
                            new WorkOnEventThread().UpdateTextArea("You Reseived NACK response\n");
                        }
                        CurrentDataSize = 0;
                        for (Position = 0; Position < TotalAPPCode.length; Position += CurrentDataSize) {
                            if (response != OTA_ERROR_OK) {
                                break;
                            }
                            CurrentDataSize = ((TotalAPPCode.length - Position) >= OTA_MAX_DATA) ? OTA_MAX_DATA : (TotalAPPCode.length - Position);
                            new WorkOnEventThread().UpdateTextArea("Sending Data Packet...\n");
                            response = OTA_SendDataPacket(TotalAPPCode, Position, CurrentDataSize);
                            if (response == OTA_ERROR_OK) {
                                new WorkOnEventThread().UpdateTextArea("You Reseived ACK response\n");
                            } else {
                                new WorkOnEventThread().UpdateTextArea("You Reseived NACK response\n");
                            }

                            if ((Position + CurrentDataSize) < TotalAPPCode.length) {
                                new WorkOnEventThread().UpdateTextArea("[" + (Position + CurrentDataSize) / OTA_MAX_DATA + "/" + TotalAPPCode.length / OTA_MAX_DATA + "]\n");
                            }

                        }
                        new WorkOnEventThread().UpdateTextArea("Sending End Packet...\n");
                        response = OTA_SendCMDPacket(OTA_CMD_END);

                        if (response == OTA_ERROR_OK) {
                            new WorkOnEventThread().UpdateTextArea("You Reseived ACK response\n");
                            new WorkOnEventThread().UpdateTextArea("Flashing Done Successfully :) \n");
                        } else {
                            new WorkOnEventThread().UpdateTextArea("You Reseived NACK response\n");
                            new WorkOnEventThread().UpdateTextArea("Flashing Failed :( \n");
                        }
                        ;

                    } catch (InterruptedException | IOException ex) {
                        Logger.getLogger(BootloaderGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                return null;
            }
        }.execute();

    }//GEN-LAST:event_jButton_StartFlashingActionPerformed

    private void jButton_OpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OpenFileActionPerformed
        // TODO add your handling code here:
        JFileChooser FileChooser = new JFileChooser();
        int FileChooserResponse = FileChooser.showOpenDialog(null);
        if (FileChooserResponse == JFileChooser.APPROVE_OPTION) {
            file = new File(FileChooser.getSelectedFile().getAbsolutePath());
            jTextField_FilePath.setText(" " + FileChooser.getSelectedFile().getAbsolutePath());
            jTextArea_OutputScreen.append("You Choose: " + FileChooser.getSelectedFile().getName() + "\n");

            try {
                TotalAPPCode = Files.readAllBytes(file.toPath());
                jTextArea_OutputScreen.append("File Total Size=" + TotalAPPCode.length + "[Bytes]\n");
                if (TotalAPPCode.length > OTA_MAX_CODE_SIZE) {
                    jTextArea_OutputScreen.append("Max Code size can be used on stm32f446RE is" + OTA_MAX_CODE_SIZE + "[Bytes]\n");
                    jTextArea_OutputScreen.append("Since i just erase Sections 5,6,7\n ");
                }
            } catch (IOException ex) {
                Logger.getLogger(BootloaderGUI.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton_OpenFileActionPerformed

    public static void main(String[] args)  {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new BootloaderGUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(BootloaderGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Connect;
    private javax.swing.JButton jButton_Disconnect;
    private javax.swing.JButton jButton_OpenFile;
    private javax.swing.JButton jButton_StartFlashing;
    private javax.swing.JComboBox<String> jComboBox_BaudRate;
    private javax.swing.JComboBox<String> jComboBox_ComPort;
    private javax.swing.JComboBox<String> jComboBox_DataBits;
    private javax.swing.JComboBox<String> jComboBox_ParityBits;
    private javax.swing.JComboBox<String> jComboBox_StopBits;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar_ComStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_OutputScreen;
    private javax.swing.JTextField jTextField_FilePath;
    // End of variables declaration//GEN-END:variables

}
